# Dockerfile.dev - Frontend Vue 3 + Vite + pnpm + Bootstrap

# Etapa base
FROM node:22.1.0

# Diretório de trabalho
WORKDIR /app

# Instala pnpm globalmente
RUN npm install -g pnpm

RUN echo "VITE_API_URL=${VITE_API_URL}" > .env

# Copia arquivos de dependência primeiro
COPY package.json pnpm-lock.yaml ./


# Instala dependências
RUN pnpm install --no-frozen-lockfile

# Copia o restante do projeto
COPY . .

# Expõe a porta do Vite (3000 padrão)
EXPOSE 3000

# Comando padrão
CMD ["pnpm", "run", "dev"]
