services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: LudoLivre
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      args:
        - API_URL=${API_URL:-http://localhost:5000}
    container_name: backend
    ports:
      - "5000:5000"
      - "5678:5678"
    depends_on:
      - mysql
    environment:
      FLASK_APP: main.py
      PYTHONUNBUFFERED: 1
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: mysql
      DB_NAME: LudoLivre
      WAIT_FOR_DEBUGGER: false
    volumes:
      - ./backend:/app
      - /app/arquivos
    command: ["python", "entryPoint.py"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: sh -c "pnpm run dev"

volumes:
  mysql_data:
