FROM python:3.13.2-alpine3.21

WORKDIR /app

RUN apk add --no-cache bash
RUN pip install debugpy

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

COPY . .

ENV PYTHONUNBUFFERED=1

CMD ["sh", "-c", "sleep 10 && flask --app main run --host=0.0.0.0 --debug"]
