/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ButtonLoading: typeof import('./components/ButtonLoading.vue')['default']
    Carrossel: typeof import('./components/Carrossel.vue')['default']
    ConfirmModal: typeof import('./components/ConfirmModal.vue')['default']
    GameLibrary: typeof import('./components/GameLibrary.vue')['default']
    LoadingSpinner: typeof import('./components/LoadingSpinner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagCard: typeof import('./components/TagCard.vue')['default']
    UploadImagens: typeof import('./components/UploadImagens.vue')['default']
    Voltar: typeof import('./components/Voltar.vue')['default']
  }
}
